### ISSUE TITLE
Unable to connect frome Home assistant - socket issue?

### ISSUE THREAD

**Issue by Charly314159** [benlbrm/ha-hottoh-component#8]
Hello Benlbrm,

And first of all thank you for your awesome work.

Unfortunately *i cannot get my Edilkamin stove integrated in HA.

I am able to control it via Wifi with the Appfire (version 1.1.9.935) app where it appears with firmware 6.2.41.

I have tried to connect it with it's local IP (found in my DHCP) and using various sockets including 5001, however even if it seems to be recognized as a Edilkamin I am stuck with the following error: 

Logger: hottohpy.client
Source: /usr/local/lib/python3.10/site-packages/hottohpy/client.py:122
First occurred: 15:39:03 (4 occurrences)
Last logged: 15:39:23

Socket error: [Errno 111] Connection refused

Is there something I am doing wrong or not understanding?

Thank you in advance!

Charles

**Comment by benlbrm** [comment]
Hello,
Sometimes it fails at first startup in HA, have you tried to reboot HA with integration activated ?
Can you try to connect directly with hottohpy lib with your computer ? with following code:
`
import sys
  
# appending a path
sys.path.append('src')
from hottohpy import Hottoh
import time
stove = Hottoh(address="YOUR_IP_ADDRESS", port="5001")
stove.connect()
stove.get_temperature()`

**Comment by Charly314159** [comment]
Thank you for your quick answer!

I indeed tried to restart HA and the raspberry pi several times.

I managed to run the hottohpy example and got promising return:

#### Start Stove Data's ####
Info: %s ["b'#00000C---0012INFRHOTTOH", '6.2.41', '-59', "68D5\\n'"]
Data: %s ["b'#00000C---005EDATR0", '85', '0', '1', '9', '11', '1', '1', '2', '173', '190', '50', '350', '-435', '260', '50', '350', '-435', '0', '0', '0', '272', '0', '5', '1', '5', '0', '5', '5', '4', '0', '0', '4', '5', '5', '4', "324F\\n'"]
Data2: %s ["b'#00000C---003BDATR2", '1', '0', '0', '0', '0', '-435', '0', '0', '0', '838', '0', '0', '0', '564', '0', '0', '0', '-435', '270', '50', '350', "F663\\n'"]
_getFirmwareVersion: %s 6.2.41
_getWifiSignal: %s -59
_getPageIndex: %s b'#00000C---005EDATR0
_getManufacturer: %s EdilKamin
_getIsBitmapVisible: %s 0
_getIsValid: %s 1
_getStoveType: %s 9
_getStoveState: %s eco_stop_1_standby
_getStoveIsOn: %s on
_getEcoMode: %s on
_getChronoMode: %s off
_getTemperatureRoom1: %s 17.3
_getSetTemperatureRoom1: %s 19.0
_getSetMaxTemperatureRoom1: %s 35.0
_getSetMinTemperatureRoom1: %s 5.0
_getTemperatureRoom2: %s -43.5
_getSetTemperatureRoom2: %s 26.0
_getSetMaxTemperatureRoom2: %s 35.0
_getSetMinTemperatureRoom2: %s 5.0
_getTemperatureRoom3: %s -43.5
_getSetTemperatureRoom3: %s 27.0
_getSetMaxTemperatureRoom3: %s 35.0
_getSetMinTemperatureRoom3: %s 5.0
_getTemperatureWater: %s -43.5
_getSetTemperatureWater: %s 0.0
_getSetMaxTemperatureWater: %s 0.0
_getSetMinTemperatureWater: %s 0.0
_getSmokeTemperature: %s 27.2
_getPowerLevel: %s 0
_getSetPowerLevel: %s 5
_getSetMaxPowerLevel: %s 5
_getSetMinPowerLevel: %s 1
_getSpeedFanSmoke: %s 0
_getSpeedFan1: %s 5
_getSetSpeedFan1: %s 5
_getSetMaxSpeedFan1: %s 4
_getSpeedFan2: %s 0
_getSetSpeedFan2: %s 0
_getSetMaxSpeedFan2: %s 4
_getSpeedFan3: %s 5
_getSetSpeedFan3: %s 5
_getSetMaxSpeedFan3: %s 4
_getFlowSwitch: %s 1
_getGenericPump: %s 0
_getAirEx1: %s 0
_getAirEx2: %s 0
_getAirEx3: %s 0
_getPuffer: %s -435
_getSetPuffer: %s 0
_getSetMinPuffer: %s 0
_getSetMaxPuffer: %s 0
_getBoiler: %s 838
_getSetBoiler: %s 0
_getSetMinBoiler: %s 0
_getSetMaxBoiler: %s 0
_getDhw: %s 564
_getSetDhw: %s 0
_getSetMinDhw: %s 0
_getSetMaxDhw: %s 0
#### End Stove Data's ####

So that confirm the socket 5001 is the correct one! 
but still no luck with the integration.

Can you see anything?

**Comment by Charly314159** [comment]
Actually I am now unable to get hottohpy to connect I get the same error as in HA: "Socket error: [Errno 111] Connection refused"

I was wondering if this could be because of concurrent acces so I made sure the appfire and the HA intégration were stopped but no luck so far.

**Comment by Charly314159** [comment]
Hello benlbrm, and happy new year!

Just to let you know , I let HA keep trying in the background to connect to the stove and it finally happened. I am not sure why but it seems stable for at least 24h. 

Now everything seems to work except the "chrono_mode" that I cannot set from HA. But it's not a big deal since I plan on doing the regulation from HA.

Thanks again for your awesome work!

**Comment by benlbrm** [comment]
Hello Charly,
sorry for the delay, as far as I know, since you're able to connect with the script, the port is ok.
I know the wifi module doesn't like have multi connections at same time. When the app is connected, HA (the integration) can have problems. I don't find why actualy.
For the chrono mode, you cannot set hours and temp but you should be able to enable / disable it.

**Comment by eole210** [comment]
> Hello, Sometimes it fails at first startup in HA, have you tried to reboot HA with integration activated ? Can you try to connect directly with hottohpy lib with your computer ? with following code:
> 
> ```
> import sys
> # appending a path
> sys.path.append('src')
> from hottohpy import Hottoh
> import time
> stove = Hottoh(address="YOUR_IP_ADDRESS", port="5001")
> stove.connect()
> stove.get_temperature()
> ```

How can i run this code?
Can I run it from HA, in the Terminal maybe?
